<a href="https://colab.research.google.com/github/prof-eduardo-galego/fiap-labs-data-analysis/blob/main/Desafio_Pr%C3%A1tico_I.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Desafio Prático 1

Faz a análise de dados da Folha de Pagamento dos servidores públicos do Estado de São Paulo, com objetivo de procurar padrões sobre os dados e possíveis desvios ou irregularidades.

O dataset está disponível em: https://www.transparencia.sp.gov.br/PortalTransparencia-Report/txt/RemuneracaoAtivos.csv

Dica: Faça o download do arquivo e importe apenas os primeiros 10 registros para testar os comandos. Depois que tudo estiver correto, importe o arquivo completo.

In [8]:
import pandas as pd                         # Biblioteca para trabalhar com datasets
import numpy as np                          # Biblioteca de funções matemáticas
import matplotlib.pyplot as plt             # Biblioteca para criação de gráficos (simples)
import seaborn as sns                       # Biblioteca para criação de gráficos (avançado)

%matplotlib inline
sns.set(color_codes=True)

df = pd.read_csv("https://www.transparencia.sp.gov.br/PortalTransparencia-Report/txt/RemuneracaoAtivos.csv", encoding='latin-1', sep=';')
display(df.head(5))
print(df.shape)

,NOME,CARGO,ORGÃO,REMUNERAÇÃO DO MÊS,FÉRIAS E 13º SALÁRIO,PAGAMENTOS EVENTUAIS,LICENÇA PRÊMIO INDENIZADA,ABONO PERMANÊNCIA & OUTRAS INDENIZAÇÕES,REDUTOR SALARIAL,TOTAL LIQUÍDO (R$),GRUPO
0,A UCENA ROSA REGINALDO SILVA,ESTAGIARIO,FUND.PE.ANCHIETA-C.P.RADIO TV.,"1400,00","0,00","0,00","0,00","0,00","0,00","1400,00",ATIVOS
1,AALAN DA SILVA ARAUJO,SD 1C PM,POLICIA MILITAR SAO PAULO,"5867,32","1857,05","0,00","0,00","962,52","0,00","5222,33",ATIVOS
2,AARAN ESTEVAO LIMA BARBOSA,CAP PM,POLICIA MILITAR SAO PAULO,"18130,83","2907,64","0,00","0,00","666,36","0,00","10641,63",ATIVOS
3,AARAO HENRIQUE OLIVEIRA,POLICIAL PENAL I,SECRETARIA ADM.PENITENCIARIA,"5481,27","913,54","0,00","0,00","0,00","0,00","4443,17",ATIVOS
4,AARAO HENRIQUE OLIVEIRA,OUTROS VINCULOS,SECRETARIA ADM.PENITENCIARIA,"296,16","0,00","0,00","0,00","0,00","0,00","270,77",ATIVOS

(517532, 11)

Segue um trecho de código para auxiliar na transformação dos dados numéricos:

In [9]:
columns_to_convert = [
    'FÉRIAS E 13º SALÁRIO',
    'PAGAMENTOS EVENTUAIS',
    'LICENÇA PRÊMIO INDENIZADA',
    'ABONO PERMANÊNCIA & OUTRAS INDENIZAÇÕES',
    'REDUTOR SALARIAL',
    'TOTAL LIQUÍDO (R$)'
]

for col in columns_to_convert:
    df[col] = df[col].str.replace(',', '.', regex=False).astype(float)

# Display the data types to confirm the changes
display(df.dtypes)

NOME                                        object
CARGO                                       object
ORGÃO                                       object
REMUNERAÇÃO DO MÊS                          object
FÉRIAS E 13º SALÁRIO                       float64
PAGAMENTOS EVENTUAIS                       float64
LICENÇA PRÊMIO INDENIZADA                  float64
ABONO PERMANÊNCIA & OUTRAS INDENIZAÇÕES    float64
REDUTOR SALARIAL                           float64
TOTAL LIQUÍDO (R$)                         float64
GRUPO                                       object
dtype: object

Segue um exemplo de código que efetua a soma do total líquido agrupado por órgão:

In [10]:
# Calculate the sum of 'TOTAL LIQUÍDO (R$)' grouped by 'ORGÃO'
total_liquido_por_orgao = df.groupby('ORGÃO')['TOTAL LIQUÍDO (R$)'].sum()

# Display the result
display(total_liquido_por_orgao)

ORGÃO
AG.MET.V.PAR.L.NORTE AGEMVALE     5.268964e+04
AG.REG.SERV.PUB.DEL.TR.EST.SP     1.765327e+06
AG.REG.SERV.PUB.EST.SP ARSESP     2.264685e+06
AGENCIA MET.BAIX.SANTISTA AGEM    9.352477e+04
AGENCIA MET.CAMPINAS AGEMCAMP     8.471691e+04
                                      ...
SECRETARIA GESTAO GOVERNO DIG.    4.481769e+06
SECRETARIA JUSTICA E CIDADANIA    1.078217e+06
SECRETARIA PARC. INVESTIMENTOS    5.081876e+05
SECRETARIA POLIT. P/ MULHER       3.627153e+05
SECRETARIA SEGURANCA PUBLICA      2.504721e+08
Name: TOTAL LIQUÍDO (R$), Length: 75, dtype: float64

Dicas do que procurar:
* Qual o servidor com maior salário? Ele ganha próximo do que os outros servidores com o mesmo cargo e órgão ganham?
* Qual a média de salário de cargo e órgão? Qual destes possuem os dados mais dispersos?
* Quais servidores ganha mais em bonificações do que em salário?
* Procure uma base de dados com salários médios praticados no mercado, faça a importação e compare os salários com a média do mercado.